# Generated by Django 2.2.4 on 2019-09-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190823_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='total_views',
            field=models.PositiveIntegerField(default=9),
        ),
    ]
