# Generated by Django 2.2.4 on 2019-09-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190902_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='total_views',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
