# Generated by Django 2.2.5 on 2019-09-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', 'auto_0003_20190926_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
