# Generated by Django 2.2.5 on 2019-09-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_auto_20190927_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
